tools:
    # Code Coverage
    external_code_coverage:
        enabled: true
        timeout: 600    # Timeout in seconds.
        runs: 2    # Scrutinizer will wait for two code coverage submissions
