language: php

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master
    - /^\d+\.\d+$/

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: phpunit --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
